server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    username: leyou116
    password: leyou
    virtual-host: /leyou116
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  static:
    itemDir: D:\ly_guangzhou116\software\nginx-1.16.0\html\item
    itemTemplate: item