server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #修改springboot下springmvc上传文件大小限制
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  oss:
    accessKeyId: LTAI7FJZ5BJhTOVA
    accessKeySecret: f9ZJZEBf7RSik9trJHdWPTF67aPexK
    host: http://image.leyou.com # 访问oss的域名，很重要bucket + endpoint
    endpoint: oss-cn-beijing.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: "" # 保存到bucket的某个子目录
    expireTime: 20 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M